sudo: required
language: node_js
node_js:
- '8'
install:
- npm i npminstall && npminstall
script:
- npm run ci
after_script:
- npminstall codecov && codecov
before_script:
- docker-compose -f test/travis/compose/docker-compose.yml up -d
services:
- docker
env:
  global:
  - REDIS_INSTANCE=foo
  - secure: BDtJIXVcqAHFwJfVseQ1YWFcsoUkgKm4Cytw7qCc9qZswMFDMbxs4rdUlKX+lvZVj6++Z/z4sPohou+70TKkd7TcIX4yut4op0d/3FbP0azrVCtMo3xkzpU9Q7szez8IasvknkQ9I+zRMNE0xTOSDU6PDVmyOaDuxtRYvHg7acNlHMDSYA8yPPKtMNvnbJhKC7EjU7yaeseKJAorsl1A7lTd4r8NP5NbYdbXqE2aw9QLT684GdXixpeo6dQJqPAiJ0WkaGIJmxttbfCbJ4SwBLIEYTJ40YCig2MndhAlMntwy5Oob4qLTalbf5JRAWM9gIW9Po+JcJQ0tq8SnbO+2ipO8YxC6zuAcpwkX++iZGy3fQFmIPcmTL9ilM+NDFlmw8bTrQgdwtSBOwib+WxvlhJPLjnmqBSX6sdEwL0yiqu29ggL8+Zw20n5hjYsu6lQyyX5WEBVRtyC4lixqVvURq79GuwHUF7/+VF3dKGyKIiQCXybHO5zuG2cxaY25cwsThuos3BIgJeaBRH45ePeVz/BUduM1UiDvk8eRZufUSGSu++DyPuAc8Z9zmrDPuiunzLn9smMSaUTbFgNjdDHWhT5l8BKU0sewSv8NjdLf0kyUPiaKTe09eJHntVPOEe/x761GH69gAkUkM5BS/D0YD5zBw2rcJx5Yp8Vb4r8XhY=
  - secure: vDBVlX6+ejXnYNNVTzmLE9fdLcVIexi0BvaMnrNgCvrwX7lxebOUxwwdQB61lNysy+7SM3Ea8zFsRX2mzTIKZ6QqHgjcPqC38CNIP+3lkGFu6d/ptA3cwaixDGv+5+CGzz6D6HQbvi9YAjwarwjPbF4CjE2Xi2CSkhUfyrzVXJ5CjX2eh1QV33n4EGv5RxAOVgpYTRskLEWNoLLnZVXEyt7SxHdiZexYWNco1MnFBo7l2YRA6u43X2qv60LNpHvrIkmyS2w5Han+VcKcaXlLiRiBMC6EiM8M2EMozw27FxSjn/PrSBAw7NjJGJxwqbOjHSI5suNsyhjycWliOctZC+tZAvoV7dHr84NoA49IYLXfEvY+GCR3/c2H9xU0ST4bt8MGVI3hs5B3DeiA0Ww9roTWI6Cvy95uccEUNXM71TBFgcn5vZKFYwwpVdPRYBFzRNfm7j7cbGy1T+bA9baWE51jY1xQetXPcCPhse79e6u1SDg+fJkDxukgQH6dGlNjLOuCbzN8YVKaSoOep8iqFOyra8Nu5Pez4UeESHYBOAUFqOuweKTllgiMcEg7ibeQqgpuD+ceYe+b4szyQr1ytWvaf8oL9lkCwMtuQ4pzqkz4Cq2BKf9NaaVl2NDXe3cW45otZ3M9qtmrJmGd5v0SYpt2pW2QgFSzqsQ3YDLnoqU=
